### ISSUE TITLE
System/currentTimeMillis vs System/nanoTime

### ISSUE THREAD

**Issue by devn** [truckerpath/clj-datadog#6]
Would it be better to use nanoTime here instead of currentTimeMillis? This is after all what the `clojure.core/time` macro does.

**Comment by neverov** [comment]
@devn Thanks for the suggestion! Implemented in #7.

**Comment by neverov** [comment]
@devn the new version is available on ![clojars](https://clojars.org/clj-datadog/versions/3.0.1).
